version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm run dev
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
          parallelism: 2
          group: 2 machines