version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          command: |
            npx cypress run --record --key 2b4858de-9c71-4a91-8591-e1798025e50e
          start: npm run dev
          wait-on: 'http://localhost:3000'
          record: true